name: frankencoin_wallet
description: A Wallet for frankencoin
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.4+24

environment:
  sdk: '>=3.2.0 <4.0.0'

isar_version: &isar_version 3.1.0+1 # define the version to be used

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: ^6.3.0
  async: ^2.11.0
  auto_size_text: ^3.0.0
  basic_utils: ^5.7.0
  bech32: ^0.2.2
  bip32: ^2.0.0
  bip39: ^1.0.6
  convert: ^3.1.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.3
  erc20: ^1.0.1
  eth_sig_util: ^0.0.9
  etherscan_api:
    git:
      url: https://github.com/konstantinullrich/etherscan_api
      ref: up-to-date-dependecies
  flutter_inappwebview: ^6.0.0
  flutter_mobx: ^2.2.0+2
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.1.1
  get_it: ^7.6.7
  http: ^1.1.0
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  intl: ^0.19.0
  jazzicon: ^1.1.0
  mobx: ^2.3.0+1
  path_provider: ^2.1.3
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.2
  styled_text: ^8.1.0
  url_launcher: ^6.3.0
  walletconnect_flutter_v2: ^2.3.1
  web3dart: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  isar_generator: *isar_version
  mobx_codegen: ^2.6.0+1
  web3dart_builders: ^0.1.0


flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/images/crypto/
   - assets/images/flags/

fonts:
   - family: Lato
     fonts:
       - asset: assets/fonts/Lato-Regular.ttf
       - asset: assets/fonts/Lato-Medium.ttf
       - asset: assets/fonts/Lato-Semibold.ttf
       - asset: assets/fonts/Lato-Bold.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#FB7185"
  adaptive_icon_foreground: "assets/images/frankencoin_wallet_fg.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/frankencoin_wallet.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/frankencoin_wallet_macos.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/frankencoin_wallet_macos.png"
    icon_size: 1024
